//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Overtime
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseSetting
    {
        public int ID { get; set; }
        public string Coniguration { get; set; }
        public Nullable<int> intVal_1 { get; set; }
        public string strVal_1 { get; set; }
        public Nullable<int> intVal_2 { get; set; }
        public string strVal_2 { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
