//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Overtime
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesMaster
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeeMobile { get; set; }
        public string EmployeeEmail { get; set; }
        public string DirectManager { get; set; }
        public string WorkingOrganization { get; set; }
        public string Department { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public Nullable<bool> Login { get; set; }
        public string ReportViewRole { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string EmployeeUserName { get; set; }
        public string SubDepartment { get; set; }
        public string JobTitle { get; set; }
    }
}
