//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Overtime
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ID { get; set; }
        public string ErrorText { get; set; }
        public string ErrorProcedure { get; set; }
        public Nullable<int> ErrorScript { get; set; }
        public string ErrorUser { get; set; }
        public string ErrorNode { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
