//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Overtime
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int ID { get; set; }
        public string EventText { get; set; }
        public string EventProcedure { get; set; }
        public Nullable<int> EventScript { get; set; }
        public string EventUser { get; set; }
        public string EventNode { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
