//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Overtime
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternComunicationHandler
    {
        public long ID { get; set; }
        public string Handler { get; set; }
        public string str_Value { get; set; }
        public Nullable<int> int_Value { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
