//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Overtime
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportUserRole
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ReportUserRoles1 ReportUserRoles1 { get; set; }
    }
}
