//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Overtime
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_CurrentSessions
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string UserName { get; set; }
        public string ApiKey { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
